name: comparador
version: "1.0.0"
profile: comparador

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets: ["target", "dbt_packages"]

models:
  comparador:
    refined:
      +schema: refined
      +materialized: table
    analytics:
      +schema: analytics
      +materialized: table
